version: "3.8"

services:
  app:
    build: .
    container_name: selenium-login-load
    env_file:
      - .env
    volumes:
      - ./results:/app/results
    stdin_open: true
    tty: true
    command: >
      python -m source.main